config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'groups#index'
  resources :groups, except: [:show, :destroy] do
    resources :messages, only: [:index, :create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :users_groups
  has_many :users, through: :users_groups

  validates :name,  presence: true

  def self.search_user(word,current_user)
    User.where("name like '%" + word + "%'").where.not(id: current_user.id)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  # validates :text, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_groups
  has_many :messages
  has_many :groups, through: :users_groups

  validates :name,  presence: true
end

app/models/users_group.rb
class UsersGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @users = User.all
  end

  def create
    @group =  Group.new(group_params)
     if @group.save
       redirect_to action: 'index'
     else
       render :new
     end
  end

  def edit
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      redirect_to action: 'index'
    else
      render :edit
    end
  end

  def search
    @users  = Group.search_user(params[:word],current_user)
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @message =  Message.new
    @messages = @group.messages
    @members = @group.users
  end

  def create
    @message = current_user.messages.new(message_params)
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:text,:image).merge(group_id: params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      %p.input-form
        %input.chat-group-form__input.user-search{ placeholder: "メンバー名を入力してください", type: "text"}
      %ul.searchlists
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      %ul.saveLists
        %li.list=current_user.name
        %input{type: "hidden", name: "group[user_ids][]", value: "#{current_user.id}"}
        - @group.users.each do |u|
          - unless u.id == current_user.id
            %li.list{"data-id": "#{u.id}"}
              =u.name
              %a.rmBtn{href: "javascript:void(0)"}　削除
              %input{type: "hidden",name: "group[user_ids][]", value: "#{u.id}"}
  .chat-group-form__field.clearfix
    .chat-group-form__field--right
      = f.submit :name, value: "SAVE", disable_with: "Save Now ...", class: "chat-group-form__action-btn"

app/views/groups/_group.html.haml
=link_to  group_messages_path(group.id) do
  %li
    %p.gname
      = group.name
    %p.lmsg
      -if group.messages.present?
        = group.messages.last.text

app/views/groups/edit.html.haml
= render 'layouts/error-message'
.chat-group-form
  %h1 チャットグループ編集
  = render 'form'

app/views/groups/index.html.haml
= render 'layouts/chats'

app/views/groups/new.html.haml
= render 'layouts/error-message'
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/_chats.html.haml
.wrap
  .contents
    = render 'layouts/sidebar'
    .contents__right
      .wrap
        .contents__right__top
          %p.gpname
            = @group.name if @group
          %p.members
            %span Members:
            = render partial: 'messages/member', collection: @members
          - if @group
            %p.geditBtn
              = link_to "Edit",edit_group_path(@group)
        .contents__right__bottom
          .box46
          - if @messages
            %ul.messages
              = render @messages

  - if controller.controller_name == "messages"
    .footer
      .leftbox
      = form_for @message, url: {action: 'create'},html:{class: 'postArea  js-form', id: 'form'} do |f|
        .msgbox
          = f.text_field :text,  placeholder: "  type a text", class: "msg js-form__text-field"
          %i.fa
            = f.label :image,class: "fa fa-picture-o"
            = f.file_field :image
        = f.submit  value: "Send", class: "btn", disable_with: "submiting"

app/views/layouts/_error-message.html.haml
- if @group.errors.any?
  #error_explanation
    %h2= "#{@group.errors.count} 件のエラーがあります "
    %ul
    - @group.errors.full_messages.each do |msg|
      %li
        = msg

app/views/layouts/_flash-message.html.haml
- flash.each do |key, value|
  = content_tag :div, class:"header alert alert-#{key}" do
    %p.header__txt
      = value

app/views/layouts/_sidebar.html.haml
.contents__left
  .contents__left__top
    %p.name
      = current_user.name
    %p.awesome
      = link_to  new_group_path do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_registration_path do
        %i.fa.fa-cog
  .contents__left__bottom
    .box20
    %ul
      - if @groups.present?  
        = render @groups

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", 'http-equiv': "Content-Type" }/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    %header
    = render 'layouts/flash-message'
    = yield

app/views/messages/_member.html.haml
%span= member.name

app/views/messages/_message.html.haml
%li.message
  %p.chatName
    = message.user.name
    %span.time
      = message.created_at.to_s.gsub(/-/,"/")
  %p.message
    = message.text
  - if message.image.present? 
    %p.image
      = image_tag message.image

app/views/messages/index.html.haml
= render 'layouts/error-message'
= render 'layouts/chats'